### ISSUE TITLE
Avoid using "plus signs and Spaces" to achieve a separate effect

### ISSUE THREAD

**Issue by XoYaPeng** [Snifer/CornellNotes#3]
This is a very good Cornell note template, it seems that css code can be "minus and space", "plus and space" to achieve the separation effect, but I want to avoid using "plus and space" to achieve the separation effect, this script needs to make any improvements?

In the following figure, the left side is the source code mode in Obsidian, and the right side is the breakdown effect in preview mode.
![image](https://github.com/user-attachments/assets/a9947aab-41e3-4f9c-8390-5ad89635a5f0)

**Comment by Snifer** [comment]
In the next few days I will update the CSS as it has some changes and improvements.
